### ISSUE TITLE
[Mobile] Delete transaction

### ISSUE THREAD

**Issue by QueenTMR** [RelativeForce/MyMoney#4]
**Background**
A clear and concise description of the problem or reason for the feature.

**Task**
Add a delete button to the transaction details page.

**Images**
![image](https://user-images.githubusercontent.com/54683644/63968186-fe306380-ca96-11e9-8a86-3514528226b6.png)

**Comment by RelativeForce** [comment]
**Closing Notes**
See PR #7 for an overview of change

**Closing Images**
![image](https://user-images.githubusercontent.com/24320350/63972592-ffff2480-caa0-11e9-8829-5101b9bf537b.png)
