### ISSUE TITLE
[Mobile] Edit transaction

### ISSUE THREAD

**Issue by QueenTMR** [RelativeForce/MyMoney#6]
**Background**
A clear and concise description of the problem or reason for the feature.

**Task**
Add an edit option into the transactions details page.

**Images**
![image](https://user-images.githubusercontent.com/54683644/63970822-f96eae00-ca9c-11e9-8664-abe7ddd999d2.png)

**Comment by RelativeForce** [comment]
**Closing Notes**
See PR #8 for an overview of changes

**Closing Images**
Normal view page now has a toggle for enabling edit mode
![image](https://user-images.githubusercontent.com/24320350/63982487-9e4bb400-caba-11e9-9415-746a352a4af7.png)

When the user toggles the edit the page changes to this
![image](https://user-images.githubusercontent.com/24320350/63982595-f1256b80-caba-11e9-9fc9-442d1dfccb14.png)

Then then the user clicks update to update the transaction. Clicking update when not in edit mode shows an error.
![image](https://user-images.githubusercontent.com/24320350/63982636-229e3700-cabb-11e9-8e86-dc95f396f1ce.png)

**Comment by QueenTMR** [comment]
Edit transaction, complete.
